apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:+iFX7kCPXiw=,iv:kchUy4vh9IEx6U/06UNXjUpTiu5/CcNwyFSuOsug5kA=,tag:XkAAOsCQcl5h+oeZWBok7w==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:uBe8O2WIzfzeQ31V3ss6S4SFC5Q=,iv:rCZ2meCZ6sqAoqyGPfmCWvS8ajcOVOywASn/fHu7mJM=,tag:1OxmkheZV9PjZEt4pbsEZg==,type:str]
kind: Secret
metadata:
    name: linkding-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUmN1VzBieHg2K0lUQkJQ
            dUc2MzhpSzI0dWJneEQ5bjRvRWk0YTlSOVgwCjkrVDNqR2dmUlJiMjFkUTZWTlFH
            N0U2NjViQWQ1RWsxcExjS3JsZEZBb2cKLS0tIEVTRVpQK2NNM1g0L2JpUWo4YmFU
            ZEhDQjRKQXloMDhRZEFMSE44dndmejQKypo0sKxd7NuDsIBRLBgND7Gumg6WotpI
            21tZYTw+oMV0QW1lL/RCET6Y2pfXzWG30tkDyYEG2NG+CKJkoocr4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T16:47:59Z"
    mac: ENC[AES256_GCM,data:UoHNo/OECyV8CC3ym2I6Y9ZDR1nm8v8LavldwKcK8VBzcp9qOQrk2RUw6dHFktNpFBpCvyEw8Cqda0/uI6AVLzOEdM9VfXlzQCL1TOtnKMlXhIFNRtFLwZhJ34trjqIu6aNAsRzbR52hETtnLkMbho7zR/v6HpjPTMpFYdAISTw=,iv:M44uVBwlO0vPr7hb0GTk09Akzba89IgqNZNLtUCkBGA=,tag:1p+hHsORJ/ke7jD11pfaHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
