apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:vB/kexlfnz02vNPNTbT1OxVNo/8GOHcELI1lPtj9iSKXfyA1yuO3Yg04OhlksE+fzurNynKXxpc=,iv:6P2Xtu80N4DjOttbsWHeVKAsW/gAQqjayJnNDuuH9oM=,tag:D2gfUUcw6OrFJUwo3Zr7uQ==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSnU0WVArZ0JSdXNReUo3
            S3hyV1dNTnJkSHR1ZW42YzRldTQzWEo2SldJCmhPNW1yWWJTM3Jjb2JLMFRCSWtH
            VlYvMmtSOFpkMHk0ejdUL056QjhCdDQKLS0tIGR5c0RrU09FR1Fxcm9kSmYvMFQv
            amF5QS8zZFdmOUR0bGJVM3BEMXdJUk0KPXRCwWum8Kb32P0DO7Ye4IpG+zaemwMG
            fVD7elYm8eMCyJU0Tk9cbRcwfhSOXy7bHJfe+ANWjxFB+Qq/bKp28w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T06:29:05Z"
    mac: ENC[AES256_GCM,data:vH2iTwQhCKOuIwxZ194awAkpsC/2xJHy3Tfq+ANCk/Y7x/orf/cclMt0afklsC/K0EHuDL3wjsKLA/yPC4f8u4c/8XxLoIVw+MUUkW7VVmyk2MjOJM8F7aBlIFdZBvBT8Oygg5G/p4iFRKvonDl0YslpCSg54YUTI9xzpez1JPE=,iv:w2aUSrvGDnGzy101dlBLOYvlQIOBNq2QLgQmq0LuPco=,tag:FrsLGiUSNbcoIbkSNZbFhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
