apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: nzbget
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-downloads
  namespace: nzbget
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-csi
