apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:1iIkj6/qJBbD/D9/n3g8fJXhRh4NCK1clNzKivqU1zmBf8r4+ryLzabbrdS+8eIx6AaFWLvMqqCAtu561/ehmVLTMAHU5CYO28Rwq0cI0LvB0yuX2SiSVS7bcvd1gE7/oODzvzxf/QGf1WK2/IezlfDBrHRMbgx7P3tXbXot3mw9Vei2x9Z2H/QB17IruUCuDP0vgHN8SNGNZJpQkSv2S2V7MEdePCpZV+0Ssx7esIKlu7S/yHD3WHqesIDSrGpAhPNxiSFtZU0P0xfdkw3wIDdEb7o5kCcuTZOrlLEFVa11y89s/npUQ+jdJoI=,iv:KL+HMg6XzzyQgMMJVQ3Pno3mh+yVtQllHOdrOWpk0rA=,tag:ib08N9B4SAtarwtoZo9Vbw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaazIzd0NEMGUrYmFGOFlV
            Qis2ek1zVHhzMUZPei9ENEtQUU9NOExueG5NClk2RTA4VjMxelRaQVVKL0c4ZnRC
            Vk1JcGxtb3l0UVhGYW5XeWhYQjVNM0EKLS0tIHNTcGljYTYySFlINktjNTg1UUpB
            azI0aCtkR1oraU4yNWpCcCtidTZHSWsKmBsRO+poYhW7CBQ1RxzUXYjbWmAWP/uY
            +vox6WQIFTPlnuA56DzJtlxFfhBp0MKHVEvryW9psPx11RdGXd5WAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T19:05:59Z"
    mac: ENC[AES256_GCM,data:ILQkWeZUpjy335VEFbODk+8s6gLtInFaOZEwrX0UsvGB5PROrFqSZM1oADXZmBzBSZCs6A+pSz+WIz2J+y5plMCbXBixThwSXA9hulZFRYo6EigDTWrP/cpGHZdYmvLBHSEkPNtAhOlOH/AWyu0mDYaKFWwLFZtpHlsgg8KqOdQ=,iv:hAIIZHBVQKn5q4y8ggu8blSDRgSph8qwSMW2IRZuF3U=,tag:RF4mWWGsBGPBLUrjjLR1Fg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
