apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: networking
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.96.0.10
        searches:
          - networking.svc.cluster.local
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credentials

      - name: config
        configMap:
          name: cloudflared-config
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: networking
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: ldpi
    credentials-file: /etc/cloudflared/creds/credentials.json

    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
      # Using ClusterIP addresses directly as workaround for DNS issues
      - hostname: dashboard.homekube.dev
        service: http://10.107.187.86:80
      - hostname: linkding.homekube.dev
        service: http://10.98.55.27:9090
      - hostname: mealie.homekube.dev
        service: http://10.107.23.240:9000
      - hostname: n8n.homekube.dev
        service: http://10.105.90.19:80
      - hostname: openwebui.homekube.dev
        service: http://10.100.84.127:8080
      - service: http_status:404
