apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: networking
data:
    credentials.json: ENC[AES256_GCM,data:LM2wETHnYE49YZU0xhCBLLUb6sbEs1YOUQDWZHEvcWSk4p/Cki9ZTBFdnP5qFpuFORxDNSU+B6lOmS0EXvTEf/n/uwx29GpQDuCFUFj4rzDNHLiaCU/VGNEoAE/DSvfWc66QA3BG9Cj+9TR4hHe/fwhpdxnihmSlQGtunGWwDWRJZJkPw749mMftEpOcQa0X0qFhJUuYhpBXKfu1J6G0Dw9CYoJumO8NZiUG/wFCA1ng1oZMpAJ9IxhbYgsknjDWN64Lpdef4iEUqzRqXMkqY+n9hfkgZbius5VFxG9v5FO+v6dBI697gCgwX3g=,iv:+/xd6kjrcPu74vo6aIj6e2Iit9hRhogNRCqTj2uWt7U=,tag:lWkHZ0CuWg4EGi72UpHs0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQTdsUmhKSFd0b0Y1c25l
            OFJvWlRpVXFOVGNoNjk3UTVjSytuNTJDc200CkFJdEN5OXRPYU9pWk9RVisrdVZX
            ZXlmdm5LbVFaeHVpYVBhSElzaVVJZkkKLS0tIE4rOGR0aFAyY21HRzRvVmZrZzJi
            MG5wSzZGaHZKUWQyQVErZW5BRG14eVkKFGwonZto++Gh/2myrD4oDQUr1oJY5j56
            7v/KrLzJlto5m4imSSDHChlfklBxx44VEysZfDe3fMNonm9Bp/R0YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T08:41:45Z"
    mac: ENC[AES256_GCM,data:s+Ns9jzG8N7gMT5SGA+hetPhRwF9xaF8h1OiNHk41gyWr4G6X23XYfA4yKFM8u3PejdWSp4ng/YXUqbOhIcMc21li4JV22nZ8PWSNxkpftjrvT+6yjJPo9ZBMFuue9dNLHT5HiRKg8zujccZllCeFwps+UOK/GwuFQkpqWjbvnM=,iv:ist3u6QDNLrXbtRkT0ambFxO+/DwJRBibl6suLrRVxI=,tag:qTtaqomSLSB9kAz19TjcuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
