apiVersion: v1
kind: PersistentVolume
metadata:
  name: mealie-nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 192.168.1.200            # IP van je UGREEN
    path: /volume1/kubernetes/mealie # jouw NFS-pad
