creation_rules:
  # Encrypt tfvars files containing secrets
  - path_regex: \.tfvars$
    age: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
  # Encrypt any yaml secrets
  - path_regex: secrets\.yaml$
    age: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
