creation_rules:
  # Encrypt tfvars files containing secrets
  - path_regex: \.tfvars$
    age: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
  # Encrypt any yaml secrets
  - path_regex: secrets\.yaml$
    age: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
