apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n 
  labels:
    app: n8n
    component: configmap
data:
  NODE_ENV: "production"
  GENERIC_TIMEZONE: "Europe/Amsterdam"
  WEBHOOK_TUNNEL: "https://n8n.homekube.dev/" 
  # Database configurations
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_HOST: "192.168.1.200"
  DB_POSTGRESDB_PORT: "39087"
  # Turn on basic auth
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "n8n"
  N8N_HOST: "n8n.homekube.dev"
  N8N_PROTOCOL: "https"
  N8N_PORT: "5678"                    
  N8N_EDITOR_BASE_URL: "https://n8n.homekube.dev"
  N8N_PROXY_HOPS: "1"