apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - postgress-secrets.yaml
  - postgress-service.yaml
  - postgress-statefullset.yaml
  - secrets.yaml
  - service.yaml
  - namespace.yaml
