apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - namespace.yaml
  - n8n-db-secret.yaml
  - n8n-db-cluster.yaml
  - n8n-secrets.yaml