apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:m6wtm8gRecLCAiypnfpYRA==,iv:fb/4Arp3Rl96oFS40yohf+r/AiQks3My+FUkbjdlqfs=,tag:8Mgqfih3jkNzpOoDKvzJLw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aGFnMEd3dS9jUVZLb3M4
            aEJub3JwQzRrQUNYUWVUWWtZdzA5bEpranlNCmVQeHBsTHNhVzRhNmIvdU1obnRy
            b0ZqYlFXM3Fyd3lNamQ4dmFkM2JPQmMKLS0tIG9BZ3FFbVBiVndiNnlFNmtNSldt
            M1NpZ3NTelEwd3p6TUVmYlRvb3lkQVEKIlcvrzM3ZmmiMDqTtee51b2bJ8lqSNzu
            hyknqEvgXI4mE/vseJ7yJHO3G3RPOquYR2FCJJtNkhzEdKGr/Etj6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T08:47:52Z"
    mac: ENC[AES256_GCM,data:c9doaaGR9rJ//Kz+H4z2WUhnvPY+qnCNIigdmZtY1Pp2E+qkMI/Y/+zNVf4VuoWHjgHVkfApDZoFBMeHpkHSdivWhp4X0eApB8pApr9i01L1zkqDTEvQKMzhUsMZptuRTuOgX9/jQ3/rjXVfKYgzmwrKOAj3iNRT+NPDldkMVqw=,iv:h55y3fJaJSQgAk/wsj/Jiq5YgjZ486M4rEs58yqwHbY=,tag:D0nu1xoB8MZ31ESC7EVolQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
