apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:JxEYVCI=,iv:6TMA5erzIPECcJ82ytGqOiTHtqQM4WZ/xV/fWuGt1L8=,tag:xUo7fyTTbTR9BfnfPWt5mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWTFWZXpOWHk5U0FZRnBx
            MThWem5MeDFRWDJocnkwTnE2VnllNTlteW5RCmJERERTcEhCUG5salhkT1RNaWkw
            clpPTzdaTUdFWUJQMHRDUHZFdGxBUkkKLS0tIDk4cWs1bG9jOElGOTBYZmwwQmx2
            MVBwdEFNcklzWUUvblhYcENiUzBNMjQK5FMO2g2tuo9/JXgN0RhhjEEt5u3Cl6W0
            FnX7ulUseUwpP8DAOA0dyjJKgS+iH2mzGktMzPmD9CtL9aTxPbQtsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T18:03:47Z"
    mac: ENC[AES256_GCM,data:C9sFqRvhAzvC7VLl9+vyZhsZ+9Blqipajx6s0mtA1wflPKxcaQbH9eW7deOD8kP7b74utQFapI/oBjSi4JVH7EI9BBOIR3x3R52C5joDzGP6eVu6e3+0c76nTOCO4BXBr7Zzt2Rs0tdQX9X7Dy7wFQ/gKNx/6BH31tFgsxKBxCE=,iv:2G6X3/ljJe0dTYXjlsipijaztsm+6Uzn4HStXtDisII=,tag:QpSCV42vB7PFLzLDMXY0vA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
