apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 2 # U gebruikt 2 replicas
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: tunnel-credential

      - name: config
        configMap:
          # Cruciaal: Naam aangepast om te matchen met de verwachte ConfigMap.
          name: cloudflared-config
          items:
          - key: config.yaml
            path: config.yaml
---
# Dit ConfigMap object bevat de feitelijke tunnel-configuratie (config.yaml)
apiVersion: v1
kind: ConfigMap
metadata:
  # Cruciaal: Naam aangepast om te matchen met de Deployment mount.
  name: cloudflared-config
data:
  config.yaml: |
    # Name of the tunnel you want to run
    tunnel: ldpi
    credentials-file: /etc/cloudflared/creds/credentials.json

    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
    # Linkding Correctie: Gebruik linkding.linkding
    - hostname: linkding.homekube.dev
      service: http://linkding.linkding:9090

    # Mealie Correctie: Gebruik mealie.mealie
    - hostname: mealie.homekube.dev
      service: http://mealie.mealie:9000

    # Dit is de 'hello_world' route voor debugging
    - hostname: hello.example.com
      service: hello_world
      
    # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
    - service: http_status:404
