apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:sYO/s3F8tZRndNSeeORNZAHwHLjxXbMMMS2ITZsF5KQnVLH0zbeUWn50pODGm5lzgsRkE2IfL6TgOxb4bO0w8/v5MnAZxbbcHCCcUiYWU6A0Uqbd8J5TOPvzV3xtVNE8tlzgFJhWuBhJptPOpPgtd5741z5gWfr4k0s1Wz+f/lJOiR0iAhvIq29SIHzPOlpXx5dJWdbDQidgMQjzlYirGV1Kj0Xcn+VecjOZ2LTLAb6ArqjvFzrtdyuGkvKyyjERTI716y5t6zosAJtpChtzdEzIPt2PZ+zMYHafxZaPblPxQxMEPXSLumQRUoY=,iv:AGIDUucw8YRD5fjcdmKWPCGGMLqQg9/BsMkhLBhNxbk=,tag:/xCntVDuqqm8lvHHyVRnag==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4SVMxWTdpRHlUV3l5cHNt
            UzBsbUJCa3NOUGw2ZlJ1R3hHSDJJSnVDT3lNCjV0ZjFTTWhsRC9DRjRyS1hxOUJa
            eHN6Zm1vakQ4VVRkV1NFTThiYm9kdlEKLS0tIDkrbVN6YVc5SkFOeWJia0tRbFJX
            cW92bkNGUmdsUTVib1V6WUdRditLYUkKr3OxE+7bnSdpnJl3YjM156b5oiXy9KOh
            oZwzVhrG0UOsdTeBHbLNEMt64WdTp64TDNFHq8CZhBLwB8EQJBnlmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T16:31:27Z"
    mac: ENC[AES256_GCM,data:MEGVI5vb2gRixD4fqUP0z6UIe66fHkd9PPuq0B83UyJrREi3nqd955PGGDDgVzy+HSc561xczJa8US3ET1DF8qnx346xgL4bxfquzec22j+MBcA+KRzQrcWk56Ns0yZwnUW9a2TC2z9bfR2XIl+7p6cremqFeKk60TOEMl61zUM=,iv:3HzAcCzGk0Rf46mfHhyFVm4zTWjBUI6faOQxZEmBqB8=,tag:0fq2Ve7No3McXYa7vgCARw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
