apiVersion: v1
kind: Secret
metadata:
    name: linkding-container-env
    namespace: linkding
type: Opaque
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:AtIXb0v9KVQ=,iv:mpQh0XdAnARxPRlvLArqnK2VBLOfUJmt3XfM1XyYzis=,tag:HXA053BvuCkvCVd5X4V6sQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:rLM9D6D5HzXHuOe5X9PptnZAakBHWooLGBgsvXmSzLw=,iv:N4dWv6zbKohsfNlNVxteMVjZa9JLn1ByzcToRQv/LOk=,tag:5xPd1a/zjHUtneFV0CT79w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTEw1YXA5TFJYbW5VeXZQ
            SGM0WTk1UmhjbFVzcnp0MFM5M0VodGdqYlVZCnprakNsbTNJUFc1MEdnMy9tUnFT
            YTkzTkVvd1FoazFlMVA5ajBmeTB6bjQKLS0tIDNMZHBvT0tycVNxUVRLR2NoZFQw
            bVJvaXVNTm1NTlpIVithMWRuR3NpYXMKZHa5qtPjXDgwa/uy2R5KtXoqdLgDRpQL
            GvrO05yoQFRbkSAbLt/STRi3Y+iZPe7dNDDf4w/guk9Tk8VOaMOD5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T09:00:11Z"
    mac: ENC[AES256_GCM,data:iUlv3BQLXdYbnl1FwfXutJJmMTz9eNnWdtRYjHQ7OddIDm3rJnKL/aM6dA4upctvBgK2Q/2i6e0uKIjFtNxWloreeIA3nB/1RpBvOVYRIfmce2c+oghTa5mJjn8fkavgczzjj8jlsdqHe3SQCe5LOWd3kJ9CteRs8FMOB9sFF6k=,iv:jL6J1A0JUsEDktwbw8iBRV33xl90qhXKMVC2b7lxgPA=,tag:S1TooeyjpbY9JCSM/TWn0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
