# Bestandsnaam: clusters/staging/apps.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  
  # Ga naar de root van de apps-map
  path: ./apps 
  prune: true
  
  # BUNDEL HIER DE KUSTOMIZATIONS DIE JE WILT DEPLOYEN:
  resources:
    # Dit is het pad VANUIT de ./apps map
    - staging/linkding              
    - staging/mealie               
    - networking/cloudflare-tunnel
