# Bestandsnaam: clusters/staging/apps.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  # Nieuwe path: verwijst naar de root van alle applicaties
  path: ./apps
  prune: true
  
  # Bundelt nu direct alle afzonderlijke Kustomization-mappen:
  resources:
    - staging/linkding              # Verwijst naar apps/staging/linkding
    - staging/mealie               # Verwijst naar apps/staging/mealie
    - networking/cloudflare-tunnel # Verwijst naar apps/networking/cloudflare-tunnel (DE OPLOSSING!)
