# clusters/staging/apps.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  # Optioneel: Wacht tot de infrastructuur klaar is
  dependsOn:
    - name: networking 
  sourceRef:
    kind: GitRepository
    name: flux-system
  # PATH is de directe route naar de staging apps
  path: ./../../apps/staging 
  prune: true
