apiVersion: v1
kind: Secret
metadata:
    name: frappe-lms-secrets
    namespace: frappe-lms
type: Opaque
stringData:
    DB_ROOT_USER: ENC[AES256_GCM,data:LuDN7TQj,iv:LxwNjAYgmuT1oBt0D9cHnnP9moblKIFehDvk6CkAbW8=,tag:jMttaLOA0kjIwRs45dNbOA==,type:str]
    DB_ROOT_PASSWORD: ENC[AES256_GCM,data:6KTirLDl6jX4rCT8uTQ=,iv:8RT5YFhB1EEdLBpwRYNx5PsU9Iu+hBLxdycjqLTDz9Q=,tag:oldmqH75tvXzBJQX/5gbqA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:eXBj1XjvJFPc6b20HW4=,iv:oDdIqIPpRGNj0GcGWztSZmX/T5fFh1eyOeW+n5LnEEY=,tag:gg3NNuX26vYB6P0x41v+IA==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:CjnJH+6RFjmd6bPVP7gSEy7ej99xPYg455lwOfdgYAsvBvOn4kbBdSQtt+euqA11V7RPMGqv9ef/WGJroV1A0g==,iv:zYtyyrhVAR3kL+6S0euWnvX+KyuZRsG/g9bUB4/5yRk=,tag:PKj+BZ23f2fibGr7nbB0pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVDMzZmMwZHp2aC9ENmdL
            YkVCTWQvTW1jRWg2WFJ3aFhCbUtnRWxVUUJVCktBT1RkRGtNTnhRVU1OMk1oa0sy
            VEdDQkQ4UVhNditqK2F2RzZOQlhKUFkKLS0tIG44dWhGTmRQYzZtWWhRYno2SnlE
            cWN2Z3RYckdoY2FjbjI4aitNOGgyMEUKISkKdfXU8uhfsxuZW87AKPhAI4xYCydW
            gtyPXlO2jmyXyyHUWoh3T/Un0Hh9juGanpCDo6BIPvohGagQhxF+oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-01T15:17:32Z"
    mac: ENC[AES256_GCM,data:Pw/EAhyVpFW5r0MlqXZO7JdznllZ1U+B693MpLMLrRPJ9Vnt24LlfDQU2Kvk6dL4V+IPPsxJTYCuJVMzq75rHMO9ZC1UtjBV+LbTVcgjj26S0zYZfbL6KgbrXsVTSDY2pu7tPUFrPaFJ+/ExCp8G4neszP4latALcIrz+EGfHzc=,iv:Ak9hQ0rChXPNb5zbEyWNNBpUKYJQB06hzPRfKnPmvyY=,tag:qy0q4t+eZpeQB+oJfcIrug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
