apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:ToOhkJHuaqQ=,iv:2ktg03VeZugJuxgzlJ4Sh5o1SKVIf2Av30VVHuhD3BM=,tag:A4UCSP/hWqU43727fvh9DA==,type:str]
    N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:taZFx+UNE3w=,iv:uBkiXU7b0G2bVmQxv0Bo73u424zpFBKyN47B+798gmI=,tag:KSWv2KA3nV9UBxkniVXobw==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:c2dM+q1A1oKZCavA4SwxvEUdgp079R7aHAAd2zxx/C3dApLtGR2kGwob8vJJ,iv:Z+dV2GfeSfbWschH2KeEIzXuxRJQeB2cpHn2vS140h8=,tag:KZcX85g7XpFnLp3AHVfFfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaHdUQW9ob2pYUVVxR1lw
            djRNaFduQTMveWFhUmZZblN0eThGRm45MVZ3CnZGd3g4VjlmelVXdWR3dW0xL1FE
            UVlqSU53S2QxWDdHdUorQmhWeDJvSGMKLS0tIGhXRUh2ejRGQ3haeGRqWFB1TWdn
            QlQvRHJyakVIOHNQQnJUWnBrbXRMU2sKBm/REJOGqyjvW3dfw4Xzpxs6kEoRjR+1
            Wz2v0MKhzvTKKmgPIs6THY+q3vRhbWfzoWIEqxcJklhPYqIif1TySA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T06:13:50Z"
    mac: ENC[AES256_GCM,data:ncnko0ArmkwxrsWlRlRTzKTMDXa7nP4ZlGgsHJpBBRRu33pdIws4eaVDzwHlpJioce8tOF2vOMm0urRWsmsaNZCHME3PAKyEEzNOwhmHWq1/PRd9ahghqVYW7XDvLV7Tv3CS1Nqz4+cpNBdau5lT0BdbmwoeBITJzUwfg+Feg0E=,iv:ytuv1uJTYpQ2gsKd1T2oiANuMHg0zfo8T+VeyoTqojg=,tag:wwZZmD7GVdd+KXjuy1ej7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
