apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:onX1Sr4fWFd7LcvJINbjRYs1PKGVpFOz,iv:Fa1WfNwGpZ5G546BSv5k/A53xjPo+3IrlB45ir10+4M=,tag:Y6yT0GR++pQ03Pv/qa3OXQ==,type:str]
    N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:V3mYjY7CY0pV+1KS0MHW+qazH97sJdF/,iv:vh/os5ihDXN5YociuTB6LU139TRDiy2DHIb5MYMgXzg=,tag:/Vlg942XBd/FJ30uxrIXaQ==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:siqrRis9K2S7j+kS9v7lpehNLz0t+3i5+wt13AG/QPA=,iv:A5/8ZerU2mAcb1eYFypx4AUgfiNtPoviCHZkVh+q+kU=,tag:Z/e5TuppBpbW26fT7QG+rw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT1Z2M25EanZXT3RueENF
            L1Q0Y2U4eUNzdG1wY3R2MWFCd1pac3YvZTA0CkFRWk5lTk9sc1JCMlpDa3M0VEVH
            c0tRYUxhczhibzNqVy90M1BTYW55R2sKLS0tIHhwU1dCZzdYNTJBRGlKY0JsMEJ2
            SE0rcjdIYndrMTMzVnRXY29hYTRXOGMKk/LfK7XoHu6xFVdklZse1wiYLTQ6dCFH
            /w3O3NYbxl2xH0KlbS7DetkUpW2PZimaF5gafdWPUIyJKdFwe4wsCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T08:47:52Z"
    mac: ENC[AES256_GCM,data:5oectEMaFlN1F7/qZIMX3KSgjB42DwjDzdhIOgWz00iQOaw211U3u45tCK28qCSb7XHqedfYWEqVpDt+Kc8jkbtt8Rhhpw+4/jS9h4bZABytSZ6CZ2YQg2DrVVz6Qs5ASaEWkXbcm2YViByuYQnEI3Q2xCKXWjrVUJ6TkYD/NK8=,iv:Up9qLRxr/i/OvjBKjQzZjmFOKN0/X9OZ8RBprH9WKhc=,tag:Ge9YCdZpb94Cy0hweJHjZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
