apiVersion: v1
kind: Secret
metadata:
    name: n8n-secrets
    namespace: n8n
type: Opaque
stringData:
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:Fzz3LfG9/LfBR8ET0Zo=,iv:d1gDx1F8P59DZtpgFx25jYn9AaiFOxcc2t0KHpa40qI=,tag:qqV69gWBG9CcGQK5Ij/w5A==,type:str]
    N8N_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:7dnYuWL31rlDYHaxSti49r6sXxcVfIj1,iv:otBPBsgzu9q0xSrFZHO+y+wHlUmA0wVo4QUo3BBe8Z8=,tag:KQFdzzuvL4+bjKYLEv8NLQ==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:QzTCQtRsoqICmVSTUe/WihymPjp7rjDNcVF/Qa0av0o=,iv:9hU4jMxpGyQGcKONqFVnzo3rr+TuJi91ovwDSRp8vhg=,tag:jwXlOy8U3s/gz9kNCWUiPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYWUxYlBKNWhsRU9OQndR
            WXVSMVduV0hSUEdlKzdmckxrbXRDNkVLTGtRCmE3L25YR3l2MVk3amMzN3hKcWtx
            UDd5QTFSQzc2SXVWS0daZFlFNWVRVFEKLS0tIERmektIZnovR04ycGMwVnI3b2Z5
            cXQ2bUZiYitMZVN5dG80Z3ZhNGVpeG8KAUxz76u6EqsWzsAj1KryYF54u+Dw6+Ds
            s62II/HfBi0MtjHnmT/BAfeq+JyK8Kki5RwJbL0JJtKXnvde1KFQKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T12:10:35Z"
    mac: ENC[AES256_GCM,data:oofGlQHJwt0H7SXNWbddZRyuF+F2GHNm8FKLKuDZu1PcUo+rG0cGrZa5EViSZw8Qvx9576DKH7kp/RjmUtFy2IN1atyLfViQPj0ArT+cij0V76Bj/ClH8ULsSSj3+DVLgmXE2UapZDcDPAvamgWXGH1OxW5Wui+H7qOM+3R7mZc=,iv:IRT2ydILPzK522m9Q0pQWYa+USEGV+EA4YTb66Q//xc=,tag:5Ui4oG6kB9Z13lgHFN3bQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
