apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-superuser
    namespace: n8n
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:rAQG,iv:ciMBAk+fO2f92B2SYvicUaaekDFBtZAWGcfouq17A8k=,tag:OGWOzKY+zXpngY+0bivfiw==,type:str]
    password: ENC[AES256_GCM,data:h/2KI+4Jk/g=,iv:M80JqRN6Suxk1S3m8rCanoHCm5p2+NLgDGWTYz3DXxc=,tag:ycWQa+7ygvxU+bihF/1ntQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVlZST1BmV2V3Z0ZuN0N0
            KzJYTStrcndWWlpZL3RQRWZCd0hibGVPL1FnCjNaM2t2U2Z2Ym9wRzJyeEw5MTd3
            T0o3c1ZPNXpoWU5DMFcyN095aG1jK3MKLS0tIEN3c2R1eVErWHVDODlVU3ZBMjhG
            TlNpQ1pTamljMkhPV1JRODN5TTFXTU0KjAAEfk1NE/I69svGtRCEnOk+wY2YP/Pt
            aCLgQ1x1ouCv84AoHiEw/8/pAHYkK7Mq3THqlAKUELsSyEjNBw1Qpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T21:47:11Z"
    mac: ENC[AES256_GCM,data:YeKA6meOg3ptuEtpZHaY2LJYrhCl5zQPIZQLyXcE1As7wpCbI9+i0uEZy24rJ5eVm212SEh32usVLfSuHlY7hbWuvqm+S7+23s2bPMM/3Gk2pX7PHVdhRU+izUgcfXrPd3aqY1m2b2ezLiAF7wJJShyKiyr241NtNi5GRWQVBYw=,iv:K/QOA5AzS8+gmPpkS5v7nzWBye6JasqNUnfIDoRz7Hw=,tag:jWun8ybZTLfwkY4tCMkb9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
