apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-superuser
    namespace: n8n
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:RK5k,iv:zrPDLa9LqZNAlWtT97fPpCDGvbAgAxf5xvHdeMvN3AQ=,tag:4uQzocvnpsakft/8GdfWcA==,type:str]
    password: ENC[AES256_GCM,data:FwmF0JvT5jhc17zECXtXpVmXS1hJy0z8,iv:t9d2HPPJ/c1eQ0s/zII2aVvikc/ZSqWhyY/r88DF1lg=,tag:D/hx0Nfe1rELf1NDN5ihFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaDcyZjZManVhNVRUdHdn
            blhXMTVFM2NWS2lhYUVuSWl6NmI3V1o4NGhjCkpsdTZBck1YeHIxd2lGK3R2bkdN
            VzEzeUNxQ3RYdTJjOWZWQlg5cXFwRjgKLS0tIFJMSi9neVFheXRUMjVUV0tWOFQy
            c2w2Mi8raStreHZyTTJwaXJQK0pESncK6WHZko8mSInuuBjRNxyN7ZWEYmnDxaBH
            U2s5auhRsR8w0Gb1hS41b8L13/Vft38A5TrEBv8CVzWZdUiTKFfJFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T08:47:52Z"
    mac: ENC[AES256_GCM,data:eIJBmLFxQiOrohCmIBsRSsXfb5tEvzDyOU2J+12BVgUoDCYrV+Ua19miWmkWk9492MBZNNIHy8P6zUNlMi+Bip2/b3kKqQoDSXTkjPRxvk4CZ1QDTOxZXAA4aZdlm9Vi/k00ILQ/hRBQMShO9CnVkdJQa0GR8IAY+rmQemPYSKg=,iv:Yvo0Ck9hmmosbeytUVob9mEdgGG3dqUJdsTNfrbqHBU=,tag:8EQ9FXd4fz8Tz0I+79mVow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
