apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      securityContext:
        fsGroup: 33

      containers:
        - name: wallabag
          image: wallabag/wallabag:2.6.14
          imagePullPolicy: IfNotPresent

          securityContext:
            allowPrivilegeEscalation: false

          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: "pdo_pgsql"
            - name: SYMFONY__ENV__DATABASE_HOST
              value: "wallabag-db-rw"
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "5432"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_USER
              value: "wallabag"
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "https://wallabag.homekube.dev"
            - name: SYMFONY__ENV__FOSUSER_REGISTRATION
              value: "false"

          # haalt alleen het DB-wachtwoord uit wallabag-secrets
          envFrom:
            - secretRef:
                name: wallabag-secrets

          ports:
            - name: http
              containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
