apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wallabag-db
  namespace: wallabag
spec:
  instances: 1
  storage:
    size: 10Gi
    storageClass: local-path
  bootstrap:
    initdb:
      database: wallabag
      owner: wallabag
      secret:
        name: wallabag-db-superuser
