apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-lms-sites
  namespace: frappe-lms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frappe-lms-logs
  namespace: frappe-lms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-csi
