apiVersion: v1
kind: Secret
metadata:
    name: wallabag-db-superuser
    namespace: wallabag
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:wLftRK5iPFA=,iv:UW2rX0iGzJWcJdovO84Vm24JWQCvi8Rz1H7gJfk3XQY=,tag:d0HvQlXRQmNsCpqENB5pcA==,type:str]
    password: ENC[AES256_GCM,data:i1Lh40CxvduucL0WPKE=,iv:dWyVEYh/wwlX+zNQ/ojuDqr3K3yuvUbZNeQfx0+q6z8=,tag:aEFBxpoWMxA7DBZEKt/Ltw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWjhoeE5LazFlVHlLY2pv
            Rm16WVd4ZVNnUDRhT3J2TlNGOTR3eVlxRkgwClZaSmpCdUhPM25UVXlGRW1xcGFS
            RC9OVjRtczZpT2RScW10dWhWcE5ITWMKLS0tIHFzYUlqc3dDY2xwVlFmcjR2Y2Ny
            V0J3dXkwcjBVSjlaRXVsTFRhaTAxKzQKVPI+BDBRHc+Fb/wDCGgBxJe/tQqX7Jz1
            Xig+V+cnz2OEvuUt/+DxAGSN0TGqMKOWhOTKvZwZxLvXHD0nXkbULA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T08:33:28Z"
    mac: ENC[AES256_GCM,data:ORdIi8rneVt2nH+4HC75SEFQVY+2gSGhn9U3vzvjqWRzMrYniYWhAEd4PA0bTPBb8UQ5xAEq9q74OC9D4LWhyt6sAdaOHWNdLjaJHb81QpOvuSMQb6CqAz8NR/rmuFat9NIxixMT4zLR4zOZW460+t6oXFM1b/MQitbnxqi7vts=,iv:EwEnW6aBcCOO8HPJvP8SDFCpF2Lfi4kTHOtFeVzv2yg=,tag:WnE6zE+OMuqqKj9rgDoT6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
