apiVersion: v1
kind: Secret
metadata:
    name: wallabag-secrets
    namespace: wallabag
type: Opaque
stringData:
    SYMFONY__ENV__DATABASE_PASSWORD: ENC[AES256_GCM,data:l7ltnxq2x2VT0pO+gIo=,iv:lOLDM9TRuhBt8wZQBfL4Bu1eymDbLX+lboBWsom5L3g=,tag:j3CXElwliFGmpvIAlNEJiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bmsxNGhDZkRjTGhTOWlP
            d01RcnZtTmJEbGtiYnUxYUNCMlNiUFlUeEJRCmV2QXJLVUZNZ09ZbmdtU0N1QU8r
            OGgxSWhSOWhuekNTb3NoUzlMSFVOSlkKLS0tIHRtQ1I1bTI4d0N2TkhUV3ZuNDVl
            ZzFuV1NMUUFYUC9NdGo5RXZkYmVQZ2cKZi3QJNXI4x+SpAqveInENQk9mDb5bxrC
            YhOsU8zDTAdh3XmCVPSHp+Vv2ho2PSDX6A38FjHGXv2Lb8OcY4aCbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-05T08:33:11Z"
    mac: ENC[AES256_GCM,data:uVvvWIQH3CKUyi9J3swQN/xFeIis/8I0Y+fiyKG7ppIdXctzW4rScAqUa0ulLA4GiNslFaAfHbTU43JWzRdQCauMPR0IgdR9P00A2VqxhWbydNCl6THWxJCXnn7vI/LPX/jkxgT9Iermm448FTqw69uyJa+ajf1AzNrypcE/HDs=,iv:f+2tfRDTbh8BJ741WgmqeYBxrL1UFucTIC/vTpUWe20=,tag:z/QSk5cajxUPjI5YnG9NNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
