apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: openwebui
  labels:
    app: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      containers:
        - name: openwebui
          image: ghcr.io/open-webui/open-webui:v0.6.41
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "2048Mi"

          env:
            - name: WEBUI_AUTH
              value: "true"
            - name: WEBUI_SECRET_KEY
              value: "t0p-s3cr3t-k3y-ch4ng3-m3-l4t3r"

          volumeMounts:
            - name: data
              mountPath: /app/backend/data

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openwebui
