apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: openwebui
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:k4urgF4bUciPGlSle9nRByh5MLiHrKsx/l4Lq6U4OOemVTkvMOFi6uFajv2bJm5y/YSHJAHP+NeaCEhWqXC9Qw==,iv:vE7ZCQoiaPnXN0NAZ7Jnm9YEl7x7+eWChmqHfOTvAgk=,tag:bGwA903wy6G0PWsXnS+vJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOVh0d0IzTisrZGYzSjRS
            cGFBbEJhZjR5Wk9QeGMyMFlKaWtNa1pqVFRjCkozMVpUNTBmRER6K1ArYXJyTFQy
            blIxWnNlanRWS3NtWUdvdVJLUXdid00KLS0tIGFlNmhIbUxZSEhqS2p4QUs1SFVw
            ZVdwTkcrWGxxbVMveHZXQU5yMWVEVk0KtF9u0TK/5h64ASt4pNl++3LjqDU55Jnm
            9j4+7Tn0MjkTXQB9+f6NUrlKFy0yRG1vg9WVipKtHTHeoD/Wt3IbAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-17T12:24:09Z"
    mac: ENC[AES256_GCM,data:3NtasvNeB9j9bqoN3bl17WMR7KRUYwNpoKHeJrMRsSWGkvxi9iZ7MEfQlYBAs0D4pBy0m6PVA3QSNmQ+oBmZsjtB4ag65QPKm7PtztunQTWPE1v+GVD4fFj4ae8yx90iVgYBG+JTJsWMGDJcloKxLw9zlq77cSZgzk0k795W504=,iv:YaHIc+nVS5Hkaqlz8EwAdL5waynVS6dMMMq3/42gJsE=,tag:Xop+3aG4RJvD+rKvGGAI0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
