apiVersion: v1
kind: Secret
metadata:
    name: openwebui-secrets
    namespace: openwebui
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:pRB4vCOp3eX+XQ4lwExFXp+Qqs3cgX00LsAGcRh62jc9N8FrojLQItfslCwqRHjW,iv:U3VyMtxlb6ZqPacRMdo1rFmcdBW/S9rdKj/YVYhjQEQ=,tag:Nu/yg6fCYrrP2lQHlnWAxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQkRaNmErdURCOElXUnc3
            aXJYZjVzVENMQ1N2RHBDNzlycm5jREdqQjBFCnNmSzVXOWpOcnJ1NDZpcVowVXk0
            b3pBZTZoVEVaTDROUXdiU0dRTTVCc1kKLS0tIG5OZ1QyV011T1ZONytFSE1BUk5y
            TFJ1QU5rdFdDUGo5RWFLbVFIUDBQencKffVUXQGXXU2IFzTGR/4+MRrMFETVD6VI
            /DBo1C2CPOgNRUnvq6XkMDhgGQwlcf8vew72cdmg0qNau+bpgHdfUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-24T09:05:16Z"
    mac: ENC[AES256_GCM,data:W7HSFYEZ0e5jr+tewop/QPLqglhn+C1CHpBFK2e3spLWGDDQ1nks7FLtE8UE1rO2lYMY4VBnqxhO/nahzvL00NbVGyPL8g525K64g2iSPpKCDSk65xPj9U4GEFHjaREFF0UaB5hc8oylAQ0xXIFgqkk/9SKDjrkyquxNbHyJOKw=,iv:A8bKCLm8MLcWOd+5DDuIMoLII70YtKFq3L4nbtV8G9g=,tag:f7MTG31ajaonnhxYWSaZhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
