apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:mMgbTg67vW+/5UcVb/CBIjOCbotbfOkxvOdDURO5fPIxsrXrAlT7Ew==,iv:9VbyEnfDsKiwWP/2OAV+VEXAEYNF2vYfcDPqKKUR+1Y=,tag:cfzRYgfdxAyAGdKw+iVvPg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13vreyxm5ff3wu5agt3yfswlvc6a55k282uwa0wp8n7znd23ffsws354jyt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSEduU01TVUZGS1NvSGR6
            Rm9Ld1d3V3RVdEFaR0E5RWNKZmdvTnhYeFUwCmhkcFFRd2dqeVhBcnpZSFVhSUds
            ZTFXci83bXFYRSttakRzL2pEamNjUmcKLS0tIHkxcW40Z3ZCdWRFamI3b2Z0Nzh1
            L3hkREdDTXlzK0l2a1lXckkzQ29WaUkKfHgcCXqxjKr0QdJ2y05YPDcFPMNOKEnb
            susihTGRIpkXb9TNwrI2mDxrNoT77T8bd6NRhJvSVhpQi06loEuNvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T06:22:10Z"
    mac: ENC[AES256_GCM,data:6O5W31TQsj0nKuNVGTLRGim0exZrUxFfbI1HjkCy2npmsETKzlFKVMdT1S5eH7lKA0Kg5JqxZrSWt1N4pMsErTsHm5L182NC7laLbp3GS+UxbjTyBiBNJm2pFPIHbXqp8ahR8v55DxQkpMEdMLvZFuINVtMjKACP/hgClNoTSjw=,iv:B/kcgv2APmPDI+H5CRSRNtUWq5e8fo47K/kdVlaME6g=,tag:6+lW/Z/C+UUCutx3MNxrSQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
