apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:YAi0YydELpDuUHci8Kikmy4FirULRF1OTzFrTELRumxDrTFYQ9yYLwYf5TP92luQKHcSgdKAuBQ=,iv:WbYdqXpu+l/qjujyi3xexA1B23VYYIkt5zZ7frtHkV8=,tag:MesrxlHR83RfWKsKwoGjSQ==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age194krt8q7cvkvl0vu7n6n3u8y8g8rxhr7h39ahzxvgy4hth3hcumqn6m8tt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTUo1VUhGUGlUcVBMclg2
            RDRMVmI0R3Z1cFM3T25vTnQzcVBUbzZoTzJzCmV6WFZmSU9uTkh2bWhzVmlkWk8v
            NG5uQmFjQmxpZ0ZZelNPalVPT2c4ajQKLS0tIHg3Q2plM1BNd0RRWERIN2J2ZDJX
            QUh2NDcwaTIwblk5dk1sWTZRdzJnSVUK0/hUYqHp0x50pMIwBwhQEfG5wfJiGoen
            ByMZGCx1sfSLBCRDN3QslEsRO808wz7bIGPUBbL0eEM1yV3zBugGCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T07:44:13Z"
    mac: ENC[AES256_GCM,data:FMXapM44DZJLdHPOHtohR7ol0DuiozE+SycQVTyGE8rloIBsMO+IaqfHIc+z8/SX4NHdmbKCnme/Fcn/VTpJon3CYBjyDOkIMIwHiN9k2OAIJMiUx42vAibQcms4DJNAml2h6ScxT7o4GZRySAfQvGdqnD6qgDICB5mxwcT5jKk=,iv:tSEjERLUoWJ2KXOBKzlLSXnRtokdOzkCGGj014mTI+c=,tag:IZBRoOEfjtk5qIYaNDy8xg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
